// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyho7_7TOnYWIHrAHPKhpLPyv0r7y94BY',
    appId: '1:398400091856:web:a21b2a6376798bc4c910d5',
    messagingSenderId: '398400091856',
    projectId: 'wemotion-a87ac',
    authDomain: 'wemotion-a87ac.firebaseapp.com',
    storageBucket: 'wemotion-a87ac.appspot.com',
    measurementId: 'G-7GJN939DRK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOS7DOWaM-06AEjn-SZ1CjmxkqOBK6Z8E',
    appId: '1:398400091856:android:c42e7f21c5927894c910d5',
    messagingSenderId: '398400091856',
    projectId: 'wemotion-a87ac',
    storageBucket: 'wemotion-a87ac.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAD8wORqNUbljlIMYHK7ZS3ovW4MTvlF50',
    appId: '1:398400091856:ios:6c0f4cde43f2f552c910d5',
    messagingSenderId: '398400091856',
    projectId: 'wemotion-a87ac',
    storageBucket: 'wemotion-a87ac.appspot.com',
    androidClientId: '398400091856-dklr4tpvgbhib43v5msd1auqfak6gg37.apps.googleusercontent.com',
    iosClientId: '398400091856-q1hinufcl1nmkd3gcvnjdfb07u96vgrl.apps.googleusercontent.com',
    iosBundleId: 'com.appsrandom.flutterWeMotion',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAD8wORqNUbljlIMYHK7ZS3ovW4MTvlF50',
    appId: '1:398400091856:ios:6c0f4cde43f2f552c910d5',
    messagingSenderId: '398400091856',
    projectId: 'wemotion-a87ac',
    storageBucket: 'wemotion-a87ac.appspot.com',
    androidClientId: '398400091856-dklr4tpvgbhib43v5msd1auqfak6gg37.apps.googleusercontent.com',
    iosClientId: '398400091856-q1hinufcl1nmkd3gcvnjdfb07u96vgrl.apps.googleusercontent.com',
    iosBundleId: 'com.appsrandom.flutterWeMotion',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAyho7_7TOnYWIHrAHPKhpLPyv0r7y94BY',
    appId: '1:398400091856:web:3a0f6a6bd9380bf8c910d5',
    messagingSenderId: '398400091856',
    projectId: 'wemotion-a87ac',
    authDomain: 'wemotion-a87ac.firebaseapp.com',
    storageBucket: 'wemotion-a87ac.appspot.com',
    measurementId: 'G-62F1H4KG5C',
  );

}